"""Add new updates

Revision ID: 6f89bae9d5d3
Revises: 5b29fe3e0bd2
Create Date: 2025-11-04 00:37:29.837052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f89bae9d5d3'
down_revision: Union[str, None] = '5b29fe3e0bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('file_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_statements_file_hash'), 'statements', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statements_file_hash'), table_name='statements')
    op.drop_column('statements', 'file_hash')
    # ### end Alembic commands ###
