"""Add timezone and currency to users

Revision ID: add_user_prefs
Revises: 2882e69e9e05
Create Date: 2025-11-07 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_user_prefs"
down_revision: Union[str, None] = "2882e69e9e05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("timezone", sa.String(), nullable=False, server_default="UTC"),
    )
    op.add_column(
        "users",
        sa.Column("currency", sa.String(), nullable=False, server_default="USD"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "currency")
    op.drop_column("users", "timezone")
    # ### end Alembic commands ###
